In [39]:
from tensorflow import keras
import pandas as pd
import numpy as np
from tensorflow.keras import utils

In [40]:
keras.__version__

'2.4.0'

In [41]:
# read dataset
col_names = ["class", "Alcohol", "Malic" "acid", "Ash", "Alcalinity of ash", "Magnesium",
             "Total phenols", "Flavanoids", "Nonflavanoid phenols", "Proanthocyanins",
             "Color intensity", "Hue", "OD280/OD315 of diluted wines", "Proline" ]
dados = pd.read_csv("wine.data", names=col_names)

In [42]:
dados

class  Alcohol  Malicacid   Ash  Alcalinity of ash  Magnesium  \
0        1    14.23       1.71  2.43               15.6        127   
1        1    13.20       1.78  2.14               11.2        100   
2        1    13.16       2.36  2.67               18.6        101   
3        1    14.37       1.95  2.50               16.8        113   
4        1    13.24       2.59  2.87               21.0        118   
..     ...      ...        ...   ...                ...        ...   
173      3    13.71       5.65  2.45               20.5         95   
174      3    13.40       3.91  2.48               23.0        102   
175      3    13.27       4.28  2.26               20.0        120   
176      3    13.17       2.59  2.37               20.0        120   
177      3    14.13       4.10  2.74               24.5         96   

     Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0             2.80        3.06                  0.28             2.29   
1             2.65        2.76                  0.26             1.28   
2             2.80        3.24                  0.30             2.81   
3             3.85        3.49                  0.24             2.18   
4             2.80        2.69                  0.39             1.82   
..             ...         ...                   ...              ...   
173           1.68        0.61                  0.52             1.06   
174           1.80        0.75                  0.43             1.41   
175           1.59        0.69                  0.43             1.35   
176           1.65        0.68                  0.53             1.46   
177           2.05        0.76                  0.56             1.35   

     Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0               5.64  1.04                          3.92     1065  
1               4.38  1.05                          3.40     1050  
2               5.68  1.03                          3.17     1185  
3               7.80  0.86                          3.45     1480  
4               4.32  1.04                          2.93      735  
..               ...   ...                           ...      ...  
173             7.70  0.64                          1.74      740  
174             7.30  0.70                          1.56      750  
175            10.20  0.59                          1.56      835  
176             9.30  0.60                          1.62      840  
177             9.20  0.61                          1.60      560  

[178 rows x 14 columns]

#### Neste exercício nosso objetivo será a classificação de dados no keras. A primeira variável, identificada como classe, "class" será nosso label de classificação com 3 níveis (1,2,3). Chamaremos de y.

#### Porém ao importar as classes para y, teremos um array. Assim, este array deverá ser convertido para matriz, via utils, para ser processado no Keras

In [43]:
y = dados["class"].values
y
### o array y deverá ser convertido para matriz para ser usado no keras:

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3], dtype=int64)

In [44]:
# converter o label (array ) para matriz ( one hot )
y_train = keras.utils.to_categorical(y)
y_train
# são 3 classes, e a primeiro coluna, não representa nenhuma classe, vamos eliminar
y_train = y_train[:, 1:4]
y_train, y_train.shape

(array([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1

In [48]:
# remover a variavel dependente do dataset de entrada
dados_in = dados.iloc[:,1:13]
dados_in = dados_in.values
dados_in, dados_in.shape

(array([[14.23,  1.71,  2.43, ...,  5.64,  1.04,  3.92],
        [13.2 ,  1.78,  2.14, ...,  4.38,  1.05,  3.4 ],
        [13.16,  2.36,  2.67, ...,  5.68,  1.03,  3.17],
        ...,
        [13.27,  4.28,  2.26, ..., 10.2 ,  0.59,  1.56],
        [13.17,  2.59,  2.37, ...,  9.3 ,  0.6 ,  1.62],
        [14.13,  4.1 ,  2.74, ...,  9.2 ,  0.61,  1.6 ]]),
 (178, 12))

In [49]:
from tensorflow import keras

In [50]:
# Sequencia de pilhas lineares de rede neural
from tensorflow.keras.models import Sequential

# Importar camadas específicas que serão usadas nas redes neurais
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten

# Optimizador - Gradient Descent
from tensorflow.keras.optimizers import SGD

# utilitarios de transformação dos dados
from tensorflow.keras import utils

In [56]:
#### Construindo a rede neural 
model = Sequential() ## Instanciando a classe Sequential() para a construção da NN
# input_dim = quantidade de variáveis independentes
# kernel_initializer = iniciação dos parametros Betas e bias = normal shuffle
model.add(Dense(40, input_dim = 12, kernel_initializer = "normal", activation = "relu")) # Dense = Uma rede neural totalmente conectada
model.add(Dense(10, kernel_initializer = "normal", activation = "sigmoid")) # a camada oculta tem fução de ativação sigmoid
model.add(Dropout(0.10)) # camada para evitar o overFit.
model.add(Dense(5, kernel_initializer = "normal", activation="sigmoid"))
# 3 layers de neuronios (3 classes) - softmax para retornar a probabilidade de cada classe
model.add(Dense(3, kernel_initializer = "normal", activation="softmax")) 

In [57]:
# Otimização com Stochastic Grandient Descent
sgd = keras.optimizers.Adam(lr = 0.01, beta_1=0.9, beta_2=0.99, epsilon=0.00000001, decay = 0.0)

In [58]:
### Compilação do modelo e treino
model.compile(loss="categorical_crossentropy", optimizer = sgd, metrics=["acc"]) # use categorical_cross para classificação

In [60]:
model.fit(x= dados_in, y=y_train, epochs=100, verbose=1)
model.evaluate(x = dados_in, y = y_train, verbose=0)

Epoch 1/100
6/6 [==============================] - 0s 0s/step - loss: 0.5694 - acc: 0.6573
Epoch 2/100
6/6 [==============================] - 0s 508us/step - loss: 0.5729 - acc: 0.6629
Epoch 3/100
6/6 [==============================] - 0s 0s/step - loss: 0.5754 - acc: 0.6517
Epoch 4/100
6/6 [==============================] - 0s 1ms/step - loss: 0.5578 - acc: 0.6573
Epoch 5/100
6/6 [==============================] - 0s 894us/step - loss: 0.5706 - acc: 0.6517
Epoch 6/100
6/6 [==============================] - 0s 1ms/step - loss: 0.5569 - acc: 0.6573
Epoch 7/100
6/6 [==============================] - 0s 836us/step - loss: 0.5506 - acc: 0.6629
Epoch 8/100
6/6 [==============================] - 0s 520us/step - loss: 0.5514 - acc: 0.6573
Epoch 9/100
6/6 [==============================] - 0s 2ms/step - loss: 0.5492 - acc: 0.6573
Epoch 10/100
6/6 [==============================] - 0s 1ms/step - loss: 0.5396 - acc: 0.6629
Epoch 11/100
6/6 [==============================] - 0s 948us/step - loss:

6/6 [==============================] - 0s 836us/step - loss: 0.2468 - acc: 0.9382
Epoch 89/100
6/6 [==============================] - 0s 836us/step - loss: 0.2826 - acc: 0.8933
Epoch 90/100
6/6 [==============================] - 0s 752us/step - loss: 0.2726 - acc: 0.9101
Epoch 91/100
6/6 [==============================] - 0s 882us/step - loss: 0.3028 - acc: 0.8764
Epoch 92/100
6/6 [==============================] - 0s 1ms/step - loss: 0.2975 - acc: 0.8820
Epoch 93/100
6/6 [==============================] - 0s 744us/step - loss: 0.2692 - acc: 0.9157
Epoch 94/100
6/6 [==============================] - 0s 667us/step - loss: 0.2330 - acc: 0.9270
Epoch 95/100
6/6 [==============================] - 0s 1ms/step - loss: 0.2153 - acc: 0.9326
Epoch 96/100
6/6 [==============================] - 0s 666us/step - loss: 0.2095 - acc: 0.9382
Epoch 97/100
6/6 [==============================] - 0s 1ms/step - loss: 0.1996 - acc: 0.9494
Epoch 98/100
6/6 [==============================] - 0s 666us/step - l

[0.18049992620944977, 0.9438202381134033]