In [18]:
import numpy as np
import tensorflow as tf
import os
import matplotlib.pyplot as plt
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

In [3]:
# matriz de identidade 2 X 3
identity_matrix = tf.eye(num_rows=2, num_columns=3, dtype=tf.float32)
tf.print(identity_matrix)
identity_matrix

[[1 0 0]
 [0 1 0]]


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.]], dtype=float32)>

In [49]:
# matriz 2*3 randomicamente normalizada
a = tf.random.normal(shape=(2,3), dtype=tf.float32)
a

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.20326068,  0.82590085,  1.3784336 ],
       [ 1.0961504 , -0.5622003 , -0.8893994 ]], dtype=float32)>

In [12]:
# matriz 2 X 3 com valores constantes
b = np.array([[3,4,5],
             [6, 7,8]])
tf.constant(b, dtype=tf.int32)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 4, 5],
       [6, 7, 8]])>

In [47]:
# matriz 3X2 randomicamente uniforme
c = tf.random.uniform(shape=(3,2), dtype=tf.float32)
c

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.6832229 , 0.81882226],
       [0.885661  , 0.20817983],
       [0.59893394, 0.7280729 ]], dtype=float32)>

In [38]:
array1 = np.array([[1., 2., 3.], [-3., -7., -1.], [0., 5., -2.]])
d = tf.constant(array1)
tf.print(d)

[[1 2 3]
 [-3 -7 -1]
 [0 5 -2]]


In [42]:
a + b, tf.add(a,b)

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[3.7410874, 2.992057 , 4.772706 ],
        [7.0123234, 6.786663 , 7.7237267]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[3.7410874, 2.992057 , 4.772706 ],
        [7.0123234, 6.786663 , 7.7237267]], dtype=float32)>)

In [44]:
tf.math.subtract(b,b) , b-b

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[0, 0, 0],
        [0, 0, 0]])>,
 array([[0, 0, 0],
        [0, 0, 0]]))

In [53]:
tf.multiply(a,tf.transpose(c))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.13887234,  0.7314682 ,  0.82559067],
       [ 0.8975524 , -0.11703876, -0.6475476 ]], dtype=float32)>

In [54]:
tf.transpose(c)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.6832229 , 0.885661  , 0.59893394],
       [0.81882226, 0.20817983, 0.7280729 ]], dtype=float32)>

In [55]:
tf.linalg.det(d)

<tf.Tensor: shape=(), dtype=float64, numpy=-37.99999999999999>

In [56]:
tf.linalg.inv(d)

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[-0.5       , -0.5       , -0.5       ],
       [ 0.15789474,  0.05263158,  0.21052632],
       [ 0.39473684,  0.13157895,  0.02631579]])>