In [16]:
sentence = "o gato comeu a roupa do rei de roma".split()
sentence

['o', 'gato', 'comeu', 'a', 'roupa', 'do', 'rei', 'de', 'roma']

In [17]:
vocab = {}
for cod, token in enumerate(sentence):
    vocab[token] = cod
vocab

{'o': 0,
 'gato': 1,
 'comeu': 2,
 'a': 3,
 'roupa': 4,
 'do': 5,
 'rei': 6,
 'de': 7,
 'roma': 8}

In [25]:
sentence_transform = list(map(vocab.get, sentence)) # mapping for search token
sentence_transform

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
# A sentença acima , atualmente codificado em dicionario , pode ser representado numa matriz com one_hot_encoding

In [30]:
import numpy as np

In [31]:
# com np.eye , ao criarmos uma matriz diagonal no comprimento do vocab (dicionario), este será sua representação one-hot
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [33]:
one_hot = np.eye(len(vocab), dtype= "int")
one_hot

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [35]:
# Agora use a forma abaixo para endereçar  array apropriado:
# palavra "gato"
one_hot[vocab["gato"]]

array([0, 1, 0, 0, 0, 0, 0, 0, 0])

In [36]:
one_hot[vocab["roupa"]]

array([0, 0, 0, 0, 1, 0, 0, 0, 0])

In [45]:
def cos_similiarity(x,y): # distância entre vetores ou matrizes pela similaridade do Coseno
    return (np.dot(x,y) / ( np.linalg.norm(x) * np.linalg.norm(x) ) )

In [40]:
print(sentence), print(one_hot), print(vocab)

['o', 'gato', 'comeu', 'a', 'roupa', 'do', 'rei', 'de', 'roma']
[[1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1]]
{'o': 0, 'gato': 1, 'comeu': 2, 'a': 3, 'roupa': 4, 'do': 5, 'rei': 6, 'de': 7, 'roma': 8}


(None, None, None)

In [43]:
word_1 = one_hot[vocab["comeu"]]
word_2 = one_hot[vocab["roupa"]]
word_1, word_2

(array([0, 0, 1, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 1, 0, 0, 0, 0]))

In [47]:
# distância da similaridade do Coseno entre word1 e word2
cos_similiarity(word_1, word_2)
# a distância do coseno entre arrays one-hot-encode é igual à ZERO. Assim cos_similiarity não é aplicável nesta situação.
# sparse matrix não aceita este método de cálculo - devido a grande quantidade de zeros.

0.0

In [52]:
# convertendo de sparse matrix para Dense Matrix
# definindo um shape para o espaço vetorial:
dim = 5
#Criando o espaço vetorial com números randomicos
W = np.random.rand(len(vocab), dim).round(3)
W

array([[0.916, 0.158, 0.895, 0.964, 0.967],
       [0.585, 0.593, 0.335, 0.054, 0.764],
       [0.771, 0.149, 0.997, 0.264, 0.795],
       [0.364, 0.472, 0.609, 0.116, 0.691],
       [0.535, 0.822, 0.648, 0.765, 0.564],
       [0.234, 0.33 , 0.839, 0.526, 0.026],
       [0.37 , 0.739, 0.591, 0.714, 0.847],
       [0.875, 0.343, 0.9  , 0.935, 0.221],
       [0.956, 0.42 , 0.053, 0.67 , 0.943]])

In [55]:
# Representação densa do array word_1 ("comeu")
dense_word_1 = np.dot(word_1, W) # 1x9 e 9*5, saida = 1 * 5
dense_word_1

array([0.771, 0.149, 0.997, 0.264, 0.795])

In [56]:
# Representação densa do array word_2 ("roupa")
dense_word_2 = np.dot(word_2, W)
dense_word_2

array([0.535, 0.822, 0.648, 0.765, 0.564])

In [57]:
# identficação dos index dos vetores na matriz:
vocab["comeu"], vocab["roupa"]

(2, 4)

In [65]:
# construindo uma matriz do espaço vetorial W, somente com as palavras densas word_1, word_2
w_out_1_2 = np.zeros(shape = W.shape)
w_out_1_2[2] = dense_word_1
w_out_1_2[4] = dense_word_2
w_out_1_2 # esta é a matrix parcialment densa somente com as palavras do vocab 2 e 4

array([[0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.771, 0.149, 0.997, 0.264, 0.795],
       [0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.535, 0.822, 0.648, 0.765, 0.564],
       [0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   ]])

In [66]:
# Cálculo da distância entre word_2 e word_4:
cos_similiarity(dense_word_1, dense_word_2)

0.7919828643488159

### criando Matrix densa - WordEmbeddings with Pytorch

In [77]:
# a camada embbeding deve ser declarada como uma camada na rede neural Pytorch, assim:
import torch
import torch.nn.functional as F
import torch.nn as nn

In [70]:
embed_layer = nn.Embedding(num_embeddings=9, embedding_dim=5, _weight=torch.FloatTensor(W) ) # matriz 9 X 5 - pesos aleatorios W
idxes_tensor = torch.LongTensor([2,4])  # 2 e 4 são as posições das palavras comeu e roupa no indice original
embeded = embed_layer(idxes_tensor)

In [71]:
embed_layer.weight # pesos aleatórios da matriz 9 words POR 5 cols

Parameter containing:
tensor([[0.9160, 0.1580, 0.8950, 0.9640, 0.9670],
        [0.5850, 0.5930, 0.3350, 0.0540, 0.7640],
        [0.7710, 0.1490, 0.9970, 0.2640, 0.7950],
        [0.3640, 0.4720, 0.6090, 0.1160, 0.6910],
        [0.5350, 0.8220, 0.6480, 0.7650, 0.5640],
        [0.2340, 0.3300, 0.8390, 0.5260, 0.0260],
        [0.3700, 0.7390, 0.5910, 0.7140, 0.8470],
        [0.8750, 0.3430, 0.9000, 0.9350, 0.2210],
        [0.9560, 0.4200, 0.0530, 0.6700, 0.9430]], requires_grad=True)

In [72]:
embeded # palavras 2 e 4.

tensor([[0.7710, 0.1490, 0.9970, 0.2640, 0.7950],
        [0.5350, 0.8220, 0.6480, 0.7650, 0.5640]],
       grad_fn=<EmbeddingBackward0>)

In [89]:
# Calculando as distancias entre as palavras 2 e 4:
F.cosine_similarity(embeded[0], embeded[1], dim=0)

tensor(0.7967, grad_fn=<DivBackward0>)